modLoader="javafml"
loaderVersion="[32,)"

[[mods]]
modId="vanillahammers"
version="${file.jarVersion}"
displayName="Vanilla Hammers"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/vanillahammers.json"
authors="MelanX"
credits="Draylar made this mod for Fabric, this is just a fork for Forge."
icon="assets/vanillahammers/icon.png"
description='''
Adds a ton of new hammers to the game!
'''
[[dependencies.vanillahammers]]
    modId="forge"
    mandatory=true
    versionRange="[32,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillahammers]]
    modId="morevanillalib"
    mandatory=true
    versionRange="[1.2.5,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillahammers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.16.1,)"
    ordering="NONE"
    side="BOTH"
