modLoader="javafml"
loaderVersion="[40,)"
license="GNU General Public License 3"
issueTrackerURL="https://github.com/MelanX/vanilla-hammers/issues"

[[mods]]
modId="vanillahammers"
version="${file.jarVersion}"
displayName="Vanilla Hammers"
updateJSONURL="https://assets.melanx.de/updates/vanilla-hammers-forge.json"
authors="MelanX"
credits="Draylar made this mod for Fabric, this is just a fork for Forge."
description='''
Adds a ton of new hammers to the game!
'''

[[dependencies.vanillahammers]]
    modId="forge"
    mandatory=true
    versionRange="[40.0.3,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillahammers]]
    modId="morevanillalib"
    mandatory=true
    versionRange="[1.18.2-3.1.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillahammers]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.2,)"
    ordering="AFTER"
    side="BOTH"

[[dependencies.vanillahammers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.2, 1.19)"
    ordering="NONE"
    side="BOTH"
