modLoader="javafml"
loaderVersion="[37,)"
license="GNU General Public License 3"

[[mods]]
modId="vanillahammers"
version="${file.jarVersion}"
displayName="Vanilla Hammers"
updateJSONURL="https://raw.githubusercontent.com/MelanX/mod-updatechecker-files/master/vanillahammers.json"
authors="MelanX"
credits="Draylar made this mod for Fabric, this is just a fork for Forge."
icon="assets/vanillahammers/icon.png"
description='''
Adds a ton of new hammers to the game!
'''

[[dependencies.vanillahammers]]
    modId="forge"
    mandatory=true
    versionRange="[37.0.31,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillahammers]]
    modId="morevanillalib"
    mandatory=true
    versionRange="[1.17.1-2.0.2,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillahammers]]
    modId="libx"
    mandatory=true
    versionRange="[1.17.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillahammers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.17.1, 1.18)"
    ordering="NONE"
    side="BOTH"
