modLoader="javafml"
loaderVersion="[29,)"

[[mods]]
modId="vanillahammers"
version="${file.jarVersion}"
displayName="Vanilla Hammers"
updateJSONURL="https://raw.githubusercontent.com/MelanX/vanilla-hammers/master/update/update.json"
authors="MelanX"
credits="Draylar made this mod for Fabric, this is just a fork for Forge. Anvil in logo is trademark of MinecraftForge."
icon="assets/vanillahammers/icon.png"
description='''
Adds a ton of new hammers to the game!
'''
[[dependencies.vanillahammers]]
    modId="forge"
    mandatory=true
    versionRange="[29,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillahammers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.15,]"
    ordering="NONE"
    side="BOTH"
