modLoader="javafml"
loaderVersion="[39,)"
license="GNU General Public License 3"

[[mods]]
modId="vanillahammers"
version="${file.jarVersion}"
displayName="Vanilla Hammers"
updateJSONURL="https://assets.melanx.de/updates/vanilla-hammers-forge.json"
authors="MelanX"
credits="Draylar made this mod for Fabric, this is just a fork for Forge."
icon="assets/vanillahammers/icon.png"
description='''
Adds a ton of new hammers to the game!
'''

[[dependencies.vanillahammers]]
    modId="forge"
    mandatory=true
    versionRange="[39,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillahammers]]
    modId="morevanillalib"
    mandatory=true
    versionRange="[1.18.1-3.0.0,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillahammers]]
    modId="libx"
    mandatory=true
    versionRange="[1.18.1,)"
    ordering="NONE"
    side="BOTH"

[[dependencies.vanillahammers]]
    modId="minecraft"
    mandatory=true
    versionRange="[1.18.1, 1.19)"
    ordering="NONE"
    side="BOTH"
